### ISSUE TITLE
Error should have property "statusCode" instead of "status"

### ISSUE THREAD

**Issue by Levino** [MichielDeMey/express-jwt-permissions#14]
Usually one gets the Statuscode (e.g. 401) from the property "statusCode" and not "status".

**Comment by MichielDeMey** [comment]
Hi @Levino, for improved compatibility with `express-jwt` we've opted to copy the error class from that project.

https://github.com/auth0/express-jwt/blob/master/lib/errors/UnauthorizedError.js

You could create a ticket in that project and see if they are willing to make the change, if so we're committed to make the change as well.

**Comment by Levino** [comment]
Thanks for the quick feedback. Will try.
