### ISSUE TITLE
Permission denied when no user object is set

### ISSUE THREAD

**Issue by MichielDeMey** [MichielDeMey/express-jwt-permissions#2]
When a user object is not set, the middleware throws a permissions error.
Not having a user object simply means that the route doesn't require any authentication/authorization.

**Comment by bveenema** [comment]
> Not having a user object simply means that the route doesn't require any authentication/authorization.

Is this true? Could not having a user object actually be a malformed or bad JWT?

**Comment by gillesdemey** [comment]
This behaviour has been changed more recently, an exception is thrown when the user object wasn't found (https://github.com/MichielDeMey/express-jwt-permissions/issues/7).

**Comment by bveenema** [comment]
Sorry for my confusion, but doesn't #7 refer to the requestProperty and not a missing user object on req?

I was referring to this:
``` JavaScript
test('no user object present, should pass', function (t) {
  var req = {}
  guard.check(['ping'])(req, res, t.end)
})
```

My assertion is that if a user object is missing on req, we should validate the permissions. I wrote this test which is passing, and in I'm not sure it should.

``` JavaScript
test('this shouldn\'t pass', function (t) {
  var guard = require('../index')({
    requestProperty: 'foo',
    permissionsProperty: 'bar'
  })
  var req = { identity: { scopes: ['foobar'] } }
  guard.check('ping')(req, res, t.end)
})
```

Maybe I'm thinking about this incorrectly.

**Comment by MichielDeMey** [comment]
You are correct, it should fail on that test.
Developers will just have to make sure they don't use the `guard` middleware on unauthenticated routes, which makes sense and is more secure by default.

Will fix.

**Comment by gillesdemey** [comment]
I've created a pull request (https://github.com/MichielDeMey/express-jwt-permissions/pull/10) @MichielDeMey please review
