### ISSUE TITLE
Permission denied when using PUT method

### ISSUE THREAD

**Issue by bernardodesousa** [MichielDeMey/express-jwt-permissions#25]
Hey! I'm getting an UnauthorizedError when using the PUT method. Works with POST, so that's what I'll be using for now, but I'm curious. I think it should work just the same with all allowed methods on res.header, right?

Am I missing something?

**Comment by gillesdemey** [comment]
This middleware is agnostic to the HTTP method that is sent, can you post your route config?

**Comment by bernardodesousa** [comment]
Sure. I'll try to post the bits that seem relevant.

On an origin control middleware:
`res.header("Access-Control-Allow-Methods", "GET, POST, OPTIONS, PUT, PATCH, DELETE")
 res.header("Access-Control-Allow-Headers", "X-Requested-With, content-type, authorization")
 res.header("Access-Control-Allow-Credentials", true)
 res.setHeader("Content-Type", "application/json")
 next()`

The part that sets the user object to the request:
`router.use("/first-part-of-the-path", jwt({ secret: secret }), require("./user/user"))`

The part that checks the permission, on user/user.js (where I would prefer to use PUT):
`router.post("/second-part-of-the-path", guard.check("permission"), modify)`

The modify function:
`function modify(req, res) {
    // database stuff with req
    res.json("SUCCESS: user data updated.")
}`

It is working, but if I change that router.post to router.put, I get this:
`UnauthorizedError: Permission denied
at Object.<anonymous> (C:\path\node_modules\express-jwt-permissions\index.js:6:23)`

**Comment by MichielDeMey** [comment]
Hi! Have you tested this further? We'll probably close this issue since it's not really related to this module?

**Comment by bernardodesousa** [comment]
I have changed all my PUTs to POSTs and moved on. Not the right solution, I know, but for now it'll have to do. Feel free to close the issue. If I find the root cause of the error, I'll report back. Thank you!
