### ISSUE TITLE
Consider adding "native support"/integration for express-unless

### ISSUE THREAD

**Issue by Klooven** [MichielDeMey/express-jwt-permissions#27]
[express-unless](https://github.com/jfromaniello/express-unless) that is being used by packages like `express-jwt` allows easily to **exclude** global middleware (applied using `app.use()`) **from certain paths**.

Having support for this would make it easy for users to check for permissions on all paths except certain ones. In this case things like this could be possible (without extra config):

```js
//Check for write permission unless it's a GET request
app.use(guard.check("write").unless({method: "GET"}));

//Check for write permission unless it's the /auth endpoint
app.use(guard.check("write").unless({path: "/auth"}));

//Combined works of course aswell
app.use(guard.check("write").unless({method: "GET", path: "/auth"}));
```

Their [docs](https://github.com/jfromaniello/express-unless#usage) have instructions about how to integrate it with packages.

---
It is of course possible to use `express-unless` without "native support"/integration, but its configuration is a bit confusing and needs a bit of "mixing" and a few more lines of code on the user's side.

**Comment by MichielDeMey** [comment]
We might be able to make it an optional dependency as defined in the NPM spec https://docs.npmjs.com/files/package.json#optionaldependencies.

**Comment by gillesdemey** [comment]
I don't see a problem with adding it as a dependency, it's ~80 lines of code (4k gzipped) and does not have any further dependencies.
