### ISSUE TITLE
Exception UnauthorizedError sending HTTP code 403

### ISSUE THREAD

**Issue by saitho** [MichielDeMey/express-jwt-permissions#31]
I was wondering why the UnauthorizedError sends the HTTP code 403 (Forbidden).
Wouldn't 401 (Unauthorized) make more sense? ;)

**Comment by gillesdemey** [comment]
TL;DR `401` should be used for missing / incorrect authentication and `403` should be used for insufficient permissions or other authorization errors :)

https://httpstatuses.com/403

> If authentication credentials were provided in the request, the server considers them insufficient to grant access.

https://httpstatuses.com/401

> The request has not been applied because it lacks valid authentication credentials for the target resource. (…) If the request included authentication credentials, then the 401 response indicates that authorization has been refused for those credentials.
