### ISSUE TITLE
Cannot change `requestProperty` object.

### ISSUE THREAD

**Issue by kurtdaveting** [MichielDeMey/express-jwt-permissions#32]
Cannot seem to change the requestProperty of my user object to `payload`. Double checked `req.payload` and its working fine without the guard. 

Here's my express-JWT config:
```
let auth = {
    required: jwt({
        secret: secret,
        userProperty: 'payload',
        getToken: getTokenFromHeader
    })
}
```
signing jwt
```
    return jwt.sign({
      id: this._id,
      username: this.username,
      exp: parseInt(exp.getTime() / 1000),
      permissions: ['r','w']
    }, secret);
```
Set using `let guard = require('express-jwt-permissions')({requestProperty: 'payload'});`
Accessing it using `guard.check('r')` throws `'user object payload was not found. Check your configuration.'`

**Comment by MichielDeMey** [comment]
Which version of `jwt-express` are you using?
The documentation mentions that you should use `requestProperty `, but in your example you've configured `userProperty `. Nonetheless, looking at the code it should just be an alias.

**Comment by kurtdaveting** [comment]
Im running 5.3.1 on express-jwt.

Looking at express-jwt js file both alias should work:
```
....
 var isRevokedCallback = options.isRevoked || DEFAULT_REVOKED_FUNCTION;

  var _requestProperty = options.userProperty || options.requestProperty || 'user';
  var _resultProperty = options.resultProperty;
  var credentialsRequired = typeof options.credentialsRequired === 'undefined' ? true : options.credentialsRequired;
....
```

Tried to change the alias from `userProperty` to `requestProperty` but still to no avail. Will try to make a runkit example asap

**Comment by gillesdemey** [comment]
I threw up a quick RunKit example but could not reproduce the issue.

It features both a negative and positive case with a custom `userProperty`.

https://runkit.com/gillesdemey/express-jwt-permissions-issues-32

@kurtdaveting it would be great if you could iterate on it to more closely match your configuration.

**Comment by MichielDeMey** [comment]
In addition, check all your middleware and other dependencies.
Some are known to mutate the request object.

**Comment by kurtdaveting** [comment]
I've found the cause of the problem. 

Calling `guard.check()` first before an express-jwt rule results to not passing the request object properly.
`router.get('/foo', guard.check('root'), auth.required, function (req, res, next) {...}` 
is fixed with
`router.get('/foo', auth.required, guard.check('root'),function (req, res, next) {...}`

Overlooked this simple mistake. Thanks for the quick response!

**Comment by MichielDeMey** [comment]
Glad you found the problem. 👍
