### ISSUE TITLE
Node Testing How to stub middleware using express-jwt-permissions guard

### ISSUE THREAD

**Issue by pdonaire1** [MichielDeMey/express-jwt-permissions#33]
Hi,
I am using express-jwt-permissions and supertest but I want two things:

I want to stub the middleware that I am using.
I want to pass the guard restricction:
I'll go to share a piece of code:

```
...
MyRoles: guard.check([
    ['admin'],
    ['user']
  ])
...
```

```
app.post("/myendpoint", MyRoles, async (req, res) => {
  console.log(1)
}
```
I don't arrive to the console.log but, if I remove the middleware MyRoles everything works well.

This is my unit test:

```
it("should respond with a 200", function (done) {
    request
      .post("/myendpoint")
      .set("Authorization", "Bearer eyJhbGciOi.eyJkYXRhIjp7InVzZ")
      .expect("Content-Type", /json/)
      .expect(200)
      .end(function (err, res) {
        ...
        done()
      });
});
```
In the User interface everything works perfectly but I need the two requirements (stub the middleware and pass the middleware by token)

I am hardcoding the token but it didn't pass the middleware, always return 403.

If you have any ideas, please let me know.

Thank you very much.

**Comment by hzlmn** [comment]
You are passing incorrect `jwt` token, you need to create token with proper payload for your test. For reference https://jwt.io/

**Comment by MichielDeMey** [comment]
Nice to hear that you’ve found the issue. I’ll close this then.
