### ISSUE TITLE
Is typings available for this module? 

### ISSUE THREAD

**Issue by Manisharote** [MichielDeMey/express-jwt-permissions#36]
I am not able to find an typing for the module. For now I used a declaration file. But if it is available please let me know.

**Comment by gillesdemey** [comment]
Nope, but happy to review any PR's if anyone is willing to contribute typings :)

**Comment by AlexZeitler** [comment]
Are you still looking/open for a PR?

**Comment by gillesdemey** [comment]
Sure, send them my way :)

**Comment by AlexZeitler** [comment]
@gillesdemey PR added.

When importing `express-jwt-permissions` to a TypeScript project and adding this `index.ts`:

```typescript
import Guard from "express-jwt-permissions";
import Express from "express";

interface Request {
    user: {
        scope: Array<string>
    }
}

const invalidGuard = Guard({
    requestProperty: false,
    permissionsProperty: 123
});

invalidGuard.check(123);

const guard = Guard({
    requestProperty: 'user',
    permissionsProperty: 'scope'
});

const handler = guard.check('api');
const request: Express.Request = <unknown>{user: {scope: ['api']}} as Express.Request;
const response: Express.Response = <unknown>{} as Express.Response;

handler(request, response, () => {
    console.log(`done`);
});
```

WebStorm shows the results in the screenshot. As you can see, `invalidGuard` with wrong types on `requestProperty` and `permissionProperty` fails as well as calling `check` with a param of wrong type.

Creating a valid `guard` works without errors as you can see as well.

![image](https://user-images.githubusercontent.com/287480/56344534-f0500500-61bd-11e9-9c4a-f47809b9a3e4.png)
