### ISSUE TITLE
[Question] Purpose of this library

### ISSUE THREAD

**Issue by lonix1** [MichielDeMey/express-jwt-permissions#38]
Newbie question alert.

Why would you encode permissions in a JWT that gets sent to the user? It's true that we can detect tampering, but nonetheless, why expose this to the world?

Why not get the token, determine which user it is, then decide on which permissions to apply. A database read would be required anyway.

**Comment by gillesdemey** [comment]
The point of encoding the permissions in the JWT token is exactly to *avoid* the database lookup.

If you encode them in the token each service can determine what permissions are relevant and required before executing the requested operation. 

You also avoid having a dependency on your authorization service for every service you have deployed; this would create a star topology and is a single point of failure in most cases.

By verifying the signature of the token we can accept the encoded permissions at face value, they can not have been tampered with unless the key has been compromised.

**Comment by lonix1** [comment]
I am using basic auth and JWTs, not oauth or anything fancy. So I guess my use case is limited for now.

Your answer was very enlightening. Is that how large oauth systems  and social logins work too? The "big tech companies" work this way?
