### ISSUE TITLE
Is it possible to check multiple permissionsProperty

### ISSUE THREAD

**Issue by fbeauche** [MichielDeMey/express-jwt-permissions#39]
Auth0 released their Core authorization and if i understand correctly , when i chose to add permissions to access token, its in the "permissions" property. 

If the API is called by client_credential application,   the token will have scopes associated with this application instead of permissions. 

Could express-jwt-permissions be used to check both "permissions" and "scopes" at the same time?

**Comment by MichielDeMey** [comment]
In theory you can have 2 instances of the package, each configured for a different permissions property.

Like so:
```js
var guardScopes = require('express-jwt-permissions')({
  permissionsProperty: 'scopes'
})

var guardPermissions = require('express-jwt-permissions')({
  permissionsProperty: 'permissions'
})

app.get('/user', guardScopes.check(['thescope']), guardPermissions.check(['thepermissions']), function(req, res) { ... })
```

This will only allow the request of both permission checks pass.
I have not tested this, but it should work.
