### ISSUE TITLE
Support different delimiter for the permissions property

### ISSUE THREAD

**Issue by lchayoun** [MichielDeMey/express-jwt-permissions#41]
can you add support for a custom delimiter?
(We are using comma separated list for the permissions)

**Comment by MichielDeMey** [comment]
As far as I tell from the RFC, only a space-delimited scope string is valid.

https://tools.ietf.org/html/rfc6749#section-3.3
```
The value of the scope parameter is expressed as a list of space-
   delimited, case-sensitive strings.
```

Should you want to deviate from the official specification, I suggest you simply transform your scope string by using spaces.

e.g. `'foo,bar'.replace(/,/g, ' ')`
