### ISSUE TITLE
user object "user" was not found. Check your configuration.

### ISSUE THREAD

**Issue by fromnowhereuser** [MichielDeMey/express-jwt-permissions#45]
I dont get the error
user object "user" was not found. Check your configuration.

here my token:
{
  "role": "ADMIN",
  "name": "toto@toto.com",
  "lastConnection": "2019-06-26T06:50:52.992Z",
  "email": "toto@toto.com",
  "scope": "admin articles",
  "exp": 1561540712,
  "iat": 1561533512
}

the token is supposed to be like that ?:
{
  "role": "ADMIN",
  "name": "toto@toto.com",
  "lastConnection": "2019-06-26T06:50:52.992Z",
  "email": "toto@toto.com",
  "user": {
  "scope": "admin articles",
   }
  "exp": 1561540712,
  "iat": 1561533512
}

because it doesn't work...

**Comment by MichielDeMey** [comment]
The `user` object is set by https://github.com/auth0/express-jwt and should not be part of your token.
Please read their README for more information on how to set it up.
