### ISSUE TITLE
add a config param as a callback to determine the protections based on the given url

### ISSUE THREAD

**Issue by ajoslin103** [MichielDeMey/express-jwt-permissions#6]
I would love to be able to specify a function to be called to get the check string based on the request

```js
app.use(guard({
  getCheck: function fromReq (req) {
    return req.url.split('/')[2];
  }
}));
```

Once I saw how your code worked I made the 2nd part of the url the same as the permissons values

**Comment by MichielDeMey** [comment]
Oops, I never got around to replying to this issue. 😅

I believe it's not really the responsibility of this module to know which permissions are attached to a certain route.

To be able to do this, the middleware would have to store a state which keeps a record of all the permissions and it's associated route(s), which I would like to avoid. A state-less middleware is a happy middleware. ;)

Nonetheless, you can actually implement that logic in your encapsulating application. Simply build a hashmap of routes/permissions and write a small reducer that configures this module based on that map. Then you can re-use that same map to do lookups based on route/permissions.
