### ISSUE TITLE
I need a per-route ignore 

### ISSUE THREAD

**Issue by ajoslin103** [MichielDeMey/express-jwt-permissions#8]
I need a guard.ignore() that I can put inline on specific routes

I am using express-jwt with credentialsRequired: trueto ensure that I only accept calls that include a JWT in them

But there are a few routes for which I do not want to use guard.check()

I need to have it both ways !!

:)

**Comment by gillesdemey** [comment]
I'm not sure if I completely understand the requirement, but maybe [express-unless](https://github.com/jfromaniello/express-unless) is what you're looking for?

**Comment by ajoslin103** [comment]
it may be, I couldn't figure out how to use it in the way I need

I want _all_ routes protected by express-jwt in that a valid non-expired JWT is required for access

I want a small number of routes to not be guard'ed for permissions

I thought it would be easy enough to just not put a guard.check on those routes but that didn't seem to help -- they were then inaccessible, returning always a 401

**Comment by joeltello** [comment]
it seems that .unless() doesn't work anymore in version 0.5.0

I have express-jwt version 5.1.0 and express-jwt-permissions version 0.5.0

**Comment by benjcalderon** [comment]
@ajoslin103 Let me know if something like [this](https://github.com/MichielDeMey/express-jwt-permissions/pull/13) is what you are looking for

**Comment by ajoslin103** [comment]
I'm sorry, I should have closed this issue out.  I re-architected around the problem  express-jwt is solidly filling the bill without problems !!

thanks
al;

**Comment by gillesdemey** [comment]
For anyone still wanting to use this in tandem with `express-unless` I've whipped up a quick gist 😊

https://gist.github.com/gillesdemey/df4f9189e4338819d8bff450984db2e1
