### ISSUE TITLE
Error on Typescript compilation

### ISSUE THREAD

**Issue by GM-Alex** [MichielDeMey/express-jwt-permissions#82]
If I try to compile it with typescript I get the following error:

`node_modules/express-jwt-permissions/index.d.ts:1:10 - error TS2305: Module '"express-unless"' has no exported member 'RequestHandler'.` The Problem seems to occurs if some other module uses express-unless above 1.0.0. Maybe it would be a good idea to update the dependencies and the related typings?

**Comment by MichielDeMey** [comment]
Hi, this should be fixed in https://github.com/MichielDeMey/express-jwt-permissions/pull/80 and is released under `v1.3.7`. 👍

Let me know if the issue still persists. 🙂
